// <auto-generated />
namespace Coles.Appreciate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m02));
        
        string IMigrationMetadata.Id
        {
            get { return "201902061147042_m02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
