//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coles.Appreciate.Domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppreciateDBEntities : DbContext
    {
        public AppreciateDBEntities()
            : base("name=AppreciateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appreciation> Appreciations { get; set; }
        public virtual DbSet<AppreciationAgree> AppreciationAgrees { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Response> Responses { get; set; }
        public virtual DbSet<AppreciationReason> AppreciationReasons { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<AppreciationTarget> AppreciationTargets { get; set; }
    }
}
