//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coles.Appreciate.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appreciation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appreciation()
        {
            this.AppreciationReason = new HashSet<AppreciationReason>();
            this.AppreciationTarget = new HashSet<AppreciationTarget>();
            this.AppreciationAgree = new HashSet<AppreciationAgree>();
        }
    
        public int AppreciationId { get; set; }
        public string AppreciationText { get; set; }
        public string SourceUserId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppreciationReason> AppreciationReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppreciationTarget> AppreciationTarget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppreciationAgree> AppreciationAgree { get; set; }
        public virtual Status Status { get; set; }
    }
}
