//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coles.Appreciate.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appreciation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appreciation()
        {
            this.AppreciationReasons = new HashSet<AppreciationReason>();
            this.AppreciationAgrees = new HashSet<AppreciationAgree>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public int AppreciationId { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppreciationReason> AppreciationReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppreciationAgree> AppreciationAgrees { get; set; }
    }
}
