//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coles.Appreciate.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppreciationTarget
    {
        public int AppreciationTargetId { get; set; }
        public int AppreciationId { get; set; }
        public string UserId { get; set; }
    }
}
