//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coles.Appreciate.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReasonType
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ReasonId { get; set; }
        public string ReasonText { get; set; }
        public Nullable<System.DateTime> create_date_time { get; set; }
        public Nullable<System.DateTime> mod_date_time { get; set; }
        public string user_id { get; set; }
    }
}
